// Generated by Wrangler on Thu Sep 26 2024 01:25:53 GMT+0100 (GMT+01:00)
// by running `wrangler types`

interface Env {
	aichatkv: KVNamespace;
	MY_VARIABLE: "production_value";
	SMTP_API_KEY: string;
	GOOGLE_CLIENT_ID: string;
	GOOGLE_CLIENT_SECRET: string;
	DB: D1Database;
	AI: Ai;
}
