// Generated by Wrangler on Mon Jul 15 2024 01:20:26 GMT+0100 (GMT+01:00)
// by running `wrangler types`

interface Env {
	petboxkv: KVNamespace;
	MY_VARIABLE: "production_value";
	SMTP_API_KEY: string;
	GOOGLE_CLIENT_ID: string;
	GOOGLE_CLIENT_SECRET: string;
	DB: D1Database;
}
