// Generated by Wrangler on Sun Jul 07 2024 03:18:04 GMT+0100 (GMT+01:00)
// by running `wrangler types`

interface Env {
	sveltkit_elysia: KVNamespace;
	MY_VARIABLE: "production_value";
	SMTP_API_KEY: string;
	DB: D1Database;
}
